name: Build and deploy a container image to Azure Web Apps

on:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: omegatriageportal
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}
  AZURE_RESOURCE_GROUP: omegatriageportal_rg
  AZURE_APP_PLAN: omegatriageportal-asp
  WEBHOOK_NAME: omegatriageportalhook1


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Authenticate using a Service Principal
      uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}


    - uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL}}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push the image tagged with the git commit hash
      run: |
        cd djangoprjt
        docker build . -t ${{ env.CONTAINER_REGISTRY }}/djangoapp2:${{ github.sha }}
        docker push ${{ env.CONTAINER_REGISTRY }}/djangoapp2:${{ github.sha }} 

    - name: Create WebApp (ARM) Template
      uses: Azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./ARMTemplates/webApp.json
        parameters: ./ARMTemplates/webApp.parameters.json

# Uncomment the below action snippet if the Web app credentials are not updated as web app settings
#    - name: Set Web App ACR authentication
#      uses: Azure/appservice-settings@v1
#      with:
#        app-name: ${{ env.AZURE_WEBAPP_NAME }}
#        app-settings-json: |
#          [
#              {
#                  "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
#                  "value": "${{ secrets.REGISTRY_PASSWORD }}",
#                  "slotSetting": false
#              },
#              {
#                  "name": "DOCKER_REGISTRY_SERVER_URL",
#                  "value": "https://${{ env.CONTAINER_REGISTRY }}",
#                  "slotSetting": false
#              },
#              {
#                  "name": "DOCKER_REGISTRY_SERVER_USERNAME",
#                  "value": "${{ secrets.REGISTRY_USERNAME  }}",
#                  "slotSetting": false
#              },
#              {
#                  "name": "DOCKER_ENABLE_CI",
#                  "value": "true"
#              }
#          ]
#
#    - name: 'Deploy to Azure Web App for Container'
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: ${{ env.AZURE_WEBAPP_NAME }}
#        images: ${{ env.CONTAINER_REGISTRY }}/djangoapp2:${{ github.sha }}
#
#    #
#    - name: Create Container Registry Webhook to WebApp
#      uses: Azure/cli@1.0.4
#      with:
#        inlineScript: |
#          ci_cd_url=$(az webapp deployment container config --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP}} --enable-cd true --query CI_CD_URL --output tsv)
#          az acr webhook create --name ${{ env.WEBHOOK_NAME }} --registry ${{ env.CONTAINER_REGISTRY}} --resource-group ${{ env.AZURE_RESOURCE_GROUP}} --actions push --uri $ci_cd_url --scope djangoapp2:${{ github.sha }}